language: php

dist: bionic

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - build/cache

before_install:
 - nvm install 8
 - nvm use 8
  
install:
  - npm install
  - npx gulp init

before_script:
  - mysql -e "create database IF NOT EXISTS omeka_test;" -uroot
  - sed -i 's/^host.*/host = "localhost"/' application/test/config/database.ini
  - sed -i 's/^user.*/user = "root"/' application/test/config/database.ini
  - sed -i 's/^dbname.*/dbname = "omeka_test"/' application/test/config/database.ini

script: ./node_modules/gulp/bin/gulp.js test --continue
